### ISSUE TITLE
User is able to pay with credit card. 

### ISSUE THREAD

**Issue by Marc-Eid** [anisdzdev/CopNoDrop#19]
this is NOT necessary though. we can have static boxes for name, card number, address... etc

**Comment by Marc-Eid** [comment]
shopify for payment; (not necessary)

**Comment by rogersi9** [comment]
**Acceptance Test:**
1- User should sign in at the login page
2- User should add profits to cart
3- User presses on proceed to checkout in the cart component
4- User should fill in the delivery information 
5- User should press on next after the delivery information is valid
6- User can enter their credit cart information in the credit card payment form
7- User presses on checkout to complete the payment
8- A success or error message will appear upon termination of the transaction
